# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('attending', models.BooleanField(default=False)),
                ('allergies', models.CharField(default='', max_length=1000)),
                ('names', models.CharField(default='', max_length=5000)),
                ('favorite_song', models.CharField(default='', max_length=100)),
                ('note', models.CharField(default='', max_length=10000)),
                ('invited_date', models.DateTimeField(auto_now_add=True)),
                ('response_date', models.DateTimeField()),
            ],
        ),
    ]
