# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elopement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='allergies',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Allergies'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='favorite_song',
            field=models.CharField(blank=True, max_length=100, verbose_name='Favorite Song'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='names',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Additional Guests'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='note',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Note to the Bride & Groom'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='response_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
